
name: TestCafe Workflow
on: [push] 
  

jobs:
  build:
    name: Run TestCafe Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Install TestCafe from 'npm' and Run Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome tests"
      - name: Test Report
        uses: phoenix-actions/test-reporting@v8
        id: test-report               # Set ID reference for step
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: '**/build/test-results/test/TEST-*.xml'   # Path to test results
          reporter: jest-junit        # Format of test results
